resource_group_name = "example-resources"
location            = "East US"
storage_account_name = "examplestoracc"
key_vault_name      = "examplekeyvault"
log_analytics_workspace_name = "example-workspace"
